### ISSUE TITLE
Allow `nil` `def` in profile definition

### ISSUE THREAD

**Issue by ethomson** [mindersec/minder#4817]
### Describe the issue

If a profile uses a rule type but does not need to specify any options, then one should be able to:

```yaml
repository:
  - type: stacklok/secret_scanning
```

but `def` is required, so one must:

```yaml
repository:
  - type: stacklok/secret_scanning
    def: {}
```
